hackathon20230505/weliving_Front

.eslintrc.cjs, .gitignore, index.html, package-lock.json, package.json, src/App.css, src/App.tsx, src/index.css, src/main.tsx, src/vite-env.d.ts, tsconfig.json, tsconfig.node.json, vite.config.ts
React Vite Typescript 프로젝트를 생성하였습니다.
=> [#1] Create 🎉 Create React Vite Typescript repo

package-lock.json, package.json
`styled-components` 라이브러리 설치 시 다음과 같은 에러가 발생했습니다.
```
npm ERR! Cannot read properties of null (reading 'edgesOut')
```
해당 에러는 `styled-components` ver 6부터 해당 명령어 시 문제가 발생한다고 합니다. 그래서 다음과 같은 명령어를 통해 설치하였습니다.
```
npm install styled-components@5.3.10
```
ver6를 사용해야 할 때 @lastest 를 통해 설치할 예정입니다.
[참고사이트: npm ERR! Cannot read properties of null (reading 'edgesOut')](https://luminous24.tistory.com/269)
=> [#3] Chore ➕ Install styled-components

package-lock.json, package.json
Router 를 사용하기 위해 React Router DOM을 설치합니다.
명령어는 다음과 같습니다.
```
npm install react-router-dom
```
=> [#3] Chore ➕ Install React Router DOM

src/index.css
색상 변수를 생성하였습니다.
이는 추후 색상을 좀 더 간편하게 변경할 수 있기 위함입니다.
=> [#3] Design 💄 Create global color variable

index.html, src/index.css
Pretandard 폰트를 전역적으로 설정하였습니다.
기본 폰트는 크기 16px, weight는 400입니다.
=> [#3] Design 💄 Set Font Pretandard

package-lock.json, package.json, src/App.tsx
API 통신 시 기본 URL 설정을 합니다.
해당 설정을 완료하면 다른 위치에서 axios 객체를 호출했을 때 baseURL  주소가 기본적으로 적용됩니다.
=> [#16] Feat ✨ Set axios baseURL

src/pages/TalkingToCatIntro.tsx
Figma 기획자료 12페이지의 `고양이와 대화하기` 페이지 마크업 작업자료입니다.
=> Feat: Add TalkingToCatIntro.tsx

src/App.tsx, src/AppRouter.tsx, src/pages/Error404.tsx
`#`를 사용하지 않고 routing을 하기 위해 browser router로 변경합니다.
=> [#32] Feat: Add NotFound Page in Router

src/components/LogIn/LogInBody.tsx, src/components/LogIn/LogInHeader.tsx, src/index.css, src/pages/Intro.tsx, src/pages/LogIn.tsx
=> [#34] Feat: Implement LogIn page

src/pages/Intro.tsx
=> [#35] Design 💄 Add Kakao LogIn Button

src/components/LogIn/LogInBody.tsx
로그인 시 이메일 확인, 비밀번호 유효성 검사 기능을 추가하였습니다.
=> [#40] Feat: Add login validation

src/pages/SignUp.tsx
react import 때문에 빌드 되지 않는 문제가 발생합니다.
해당 코드 부분을 삭제합니다.
=> [#42] !HOTFIX: Remove react import

src/components/LogIn/LogInBody.tsx
로그인 페이지에 들어갔을 때 바로 유효성 검사를 하는 것이 아닌, 값을 입력 했을 때부터 유효성 검사가 되게끔 코드를 변경합니다.
=> [#52] Feat: Change login valid default value

src/apis/users/signin/signIn.ts, src/components/LogIn/LogInBody.tsx
로그인 버튼 클릭 시 로그인이 되는 기능을 추가합니다.
=> [#50] Feat: Implement LogIn when click login button

src/App.tsx, src/AppRouter.tsx, src/components/Intro/Header.tsx, src/components/LogIn/LogInBody.tsx, src/components/LogIn/LogInHeader.tsx, src/components/SignUp/SignUpBody.tsx, src/components/SignUp/SignUpHeader.tsx, src/pages/Error404.tsx, src/pages/Intro.tsx, src/pages/LogIn.tsx, src/pages/SignUp.tsx, src/utils/isValid/isValidUserData.ts
=> [#55] Design: Publishing Sign up Page

package-lock.json, package.json, src/components/MainContent/BackgroundFirst.tsx, src/components/OnBording/Background.tsx, src/pages/MainContentFirst.tsx, src/pages/OnBording.tsx
=> [#59] Feat: Add Type Effect Module

src/components/Home/HomeBody.tsx, src/pages/ViewMyLetter.tsx, src/pages/ViewOtherLetter.tsx, src/pages/WriteLetter.tsx
=> [#57] Feat: Implement Home page

src/AppRouter.tsx, src/components/WriteLetter/WriteLetterBody.tsx, src/components/WriteLetter/WriteLetterHeader.tsx, src/components/WriteLetter/atoms/isValidPostAtom.tsx, src/index.css, src/pages/CollectPersonalInfo.tsx, src/pages/PrivacyPolicy.tsx, src/pages/TermsOfService.tsx, src/pages/WriteLetter.tsx
=> [#58] Design: Implement Write Letter page

src/components/MainContent/BackgroundFirst.tsx, src/components/OnBording/Background.tsx
=> [#66] Fix : Build Error Fix

src/components/Home/HomeBody.tsx
임의로 프론트 서버로 연결해놓은 img path를 ftp path로 변경하였습니다.
=> !HOTFIX: chage img path

.github/workflows/main.yml
GitHub Action 대상 브런치를 (master, develop) 에서 메인 브런치에 맞게 main 으로 변경
=> Github Action 브런치 이름 변경

.github/workflows/main.yml
Github Action 환경 변수를 "envs" 오타 발생하여 "env" 로 수정 하여 저장하였음.
=> Github Action "envs" 오타 수정

src/components/Home/HomeBody.tsx
=> GitHub Action 배포 테스트

src/components/Home/HomeBody.tsx
=> GitHub Action 배포 테스트 #2

src/components/AfterWrite/YourHelp.tsx, src/components/Common/ResizableBottomSheet.tsx, src/components/LogIn/LogInBody.tsx, src/components/SignUp/SignUpBody.tsx, src/components/WriteLetter/WriteLetterBody.tsx, src/components/WriteLetter/WriteLetterHeader.tsx, src/pages/Error404.tsx, src/pages/FindPW.tsx, src/pages/KakaoSignUp.tsx, src/pages/LogIn.tsx
typescript lint 로 인한 에러를 고쳤습니다.
=> !HOTFIX: Fixed typescript error

src/components/AfterWrite/YourHelp.tsx, src/components/LogIn/LogInBody.tsx, src/components/ViewMyLetter/LetterHeader.tsx, src/components/ViewMyLetter/ViewMyLetterPost.tsx, src/components/WriteLetter/WriteLetterHeader.tsx, src/pages/Intro.tsx, src/pages/KakaoSignUp.tsx, src/pages/ViewMyLetter.tsx, src/utils/interceptors/onRequest.ts, src/utils/interceptors/onResponse.ts
=> !HOTFIX: Fix build error

src/components/ChangeUserInfo/ChangeUserInfoBody.tsx, src/components/Common/BottomSheet.tsx, src/components/Common/CommonContentContainer.tsx, src/components/Common/ResizableBottomSheet.tsx, src/components/Home/HomeBody.tsx, src/components/Home/HomeHeader.tsx, src/components/Intro/IntroBackground.tsx, src/components/MainContent/BackgroundSecond.tsx, src/components/MainContent/MainContentSecondWordFirst.tsx, src/components/ViewMyLetter/LetterHeader.tsx, src/components/WriteCard/WriteCardBody.tsx, src/pages/Intro.tsx, src/pages/MainContentSecond.tsx, src/pages/OnBording.tsx
=> [#94] fix Animation Effect

src/apis/users/getUserEmail.ts, src/components/ChangeUserInfo/ChangeUserInfoBody.tsx
개인 정보 변경 페이지에서 사용자 email를 가져오는 APi룰 추가하였습니다.
=> Feat: Add get user email API

package-lock.json, package.json, src/apis/users/chagepwd.ts, src/apis/users/checktwd.ts, src/apis/users/getUserEmail.ts, src/components/ChangeUserInfo/ChangeUserInfoBody.tsx
내 정보 페이지에서 비밀번호 변경하기 위한 유효성 검사와 API를 추가하였습니다.
=> Feat: Add PW change API

src/components/AfterWrite/YourHelp.tsx
=> Feat: Set Phone Verify Input's range
